# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/dell/saltbay/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/dell/saltbay/proprietary/lib/arm/cpuinfo:system/lib/arm/cpuinfo \
    vendor/dell/saltbay/proprietary/lib/arm/cpuinfo.neon:system/lib/arm/cpuinfo.neon \
    vendor/dell/saltbay/proprietary/lib/arm/libandroid_runtime.so:system/lib/arm/libandroid_runtime.so \
    vendor/dell/saltbay/proprietary/lib/arm/libandroidfw.so:system/lib/arm/libandroidfw.so \
    vendor/dell/saltbay/proprietary/lib/arm/libandroid.so:system/lib/arm/libandroid.so \
    vendor/dell/saltbay/proprietary/lib/arm/libaudioflinger.so:system/lib/arm/libaudioflinger.so \
    vendor/dell/saltbay/proprietary/lib/arm/libaudioutils.so:system/lib/arm/libaudioutils.so \
    vendor/dell/saltbay/proprietary/lib/arm/libbcc.so:system/lib/arm/libbcc.so \
    vendor/dell/saltbay/proprietary/lib/arm/libbcinfo.so:system/lib/arm/libbcinfo.so \
    vendor/dell/saltbay/proprietary/lib/arm/libbinder.so:system/lib/arm/libbinder.so \
    vendor/dell/saltbay/proprietary/lib/arm/libc_orig.so:system/lib/arm/libc_orig.so \
    vendor/dell/saltbay/proprietary/lib/arm/libc.so:system/lib/arm/libc.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcamera_client.so:system/lib/arm/libcamera_client.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcamera_metadata.so:system/lib/arm/libcamera_metadata.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcommon_time_client.so:system/lib/arm/libcommon_time_client.so \
    vendor/dell/saltbay/proprietary/lib/arm/libconnectivitymanager.so:system/lib/arm/libconnectivitymanager.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcorkscrew.so:system/lib/arm/libcorkscrew.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcrypto.so:system/lib/arm/libcrypto.so \
    vendor/dell/saltbay/proprietary/lib/arm/libcutils.so:system/lib/arm/libcutils.so \
    vendor/dell/saltbay/proprietary/lib/arm/libdl.so:system/lib/arm/libdl.so \
    vendor/dell/saltbay/proprietary/lib/arm/libdrmframework.so:system/lib/arm/libdrmframework.so \
    vendor/dell/saltbay/proprietary/lib/arm/libdvm.so:system/lib/arm/libdvm.so \
    vendor/dell/saltbay/proprietary/lib/arm/libeffects.so:system/lib/arm/libeffects.so \
    vendor/dell/saltbay/proprietary/lib/arm/libEGL.so:system/lib/arm/libEGL.so \
    vendor/dell/saltbay/proprietary/lib/arm/libETC1.so:system/lib/arm/libETC1.so \
    vendor/dell/saltbay/proprietary/lib/arm/libexpat.so:system/lib/arm/libexpat.so \
    vendor/dell/saltbay/proprietary/lib/arm/libfilterfw.so:system/lib/arm/libfilterfw.so \
    vendor/dell/saltbay/proprietary/lib/arm/libfilterpack_imageproc.so:system/lib/arm/libfilterpack_imageproc.so \
    vendor/dell/saltbay/proprietary/lib/arm/libft2.so:system/lib/arm/libft2.so \
    vendor/dell/saltbay/proprietary/lib/arm/libgabi++.so:system/lib/arm/libgabi++.so \
    vendor/dell/saltbay/proprietary/lib/arm/libft2.so:system/lib/arm/libft2.so \
    vendor/dell/saltbay/proprietary/lib/arm/libframesequence.so:system/lib/arm/libframesequence.so \
    vendor/dell/saltbay/proprietary/lib/arm/libgcam.so:system/lib/arm/libgcam.so \
    vendor/dell/saltbay/proprietary/lib/arm/libgcam_swig_jni.so:system/lib/arm/libgcam_swig_jni.so \
    vendor/dell/saltbay/proprietary/lib/arm/libgccdemangle.so:system/lib/arm/libgccdemangle.so \
    vendor/dell/saltbay/proprietary/lib/arm/libGLES_trace.so:system/lib/arm/libGLES_trace.so \
    vendor/dell/saltbay/proprietary/lib/arm/libGLESv1_CM.so:system/lib/arm/libGLESv1_CM.so \
    vendor/dell/saltbay/proprietary/lib/arm/libGLESv2.so:system/lib/arm/libGLESv2.so \
    vendor/dell/saltbay/proprietary/lib/arm/libgui.so:system/lib/arm/libgui.so \
    vendor/dell/saltbay/proprietary/lib/arm/libhardware_legacy.so:system/lib/arm/libhardware_legacy.so \
    vendor/dell/saltbay/proprietary/lib/arm/libhardware.so:system/lib/arm/libhardware.so \
    vendor/dell/saltbay/proprietary/lib/arm/libharfbuzz_ng.so:system/lib/arm/libharfbuzz_ng.so \
    vendor/dell/saltbay/proprietary/lib/arm/libharfbuzz.so:system/lib/arm/libharfbuzz.so \
    vendor/dell/saltbay/proprietary/lib/arm/libhwui.so:system/lib/arm/libhwui.so \
    vendor/dell/saltbay/proprietary/lib/arm/libicui18n.so:system/lib/arm/libicui18n.so \
    vendor/dell/saltbay/proprietary/lib/arm/libicuuc.so:system/lib/arm/libicuuc.so \
    vendor/dell/saltbay/proprietary/lib/arm/libinput.so:system/lib/arm/libinput.so \
    vendor/dell/saltbay/proprietary/lib/arm/libjnigraphics.so:system/lib/arm/libjnigraphics.so \
    vendor/dell/saltbay/proprietary/lib/arm/libjpeg.so:system/lib/arm/libjpeg.so \
    vendor/dell/saltbay/proprietary/lib/arm/libLLVM.so:system/lib/arm/libLLVM.so \
    vendor/dell/saltbay/proprietary/lib/arm/liblog.so:system/lib/arm/liblog.so \
    vendor/dell/saltbay/proprietary/lib/arm/liblightcycle.so:system/lib/arm/liblightcycle.so \
    vendor/dell/saltbay/proprietary/lib/arm/libm_orig.so:system/lib/arm/libm_orig.so \
    vendor/dell/saltbay/proprietary/lib/arm/libm.so:system/lib/arm/libm.so \
    vendor/dell/saltbay/proprietary/lib/arm/libmedia.so:system/lib/arm/libmedia.so \
    vendor/dell/saltbay/proprietary/lib/arm/libmemtrack.so:system/lib/arm/libmemtrack.so \
    vendor/dell/saltbay/proprietary/lib/arm/libnativehelper.so:system/lib/arm/libnativehelper.so \
    vendor/dell/saltbay/proprietary/lib/arm/libnbaio.so:system/lib/arm/libnbaio.so \
    vendor/dell/saltbay/proprietary/lib/arm/libnetutils.so:system/lib/arm/libnetutils.so \
    vendor/dell/saltbay/proprietary/lib/arm/libnfc_ndef.so:system/lib/arm/libnfc_ndef.so \
    vendor/dell/saltbay/proprietary/lib/arm/libOpenMAXAL.so:system/lib/arm/libOpenMAXAL.so \
    vendor/dell/saltbay/proprietary/lib/arm/libOpenSLES.so:system/lib/arm/libOpenSLES.so \
    vendor/dell/saltbay/proprietary/lib/arm/libpatts_engine_jni_api_ub.210030103.so:system/lib/arm/libpatts_engine_jni_api_ub.210030103.so \
    vendor/dell/saltbay/proprietary/lib/arm/libpixelflinger.so:system/lib/arm/libpixelflinger.so \
    vendor/dell/saltbay/proprietary/lib/arm/libpng.so:system/lib/arm/libpng.so \
    vendor/dell/saltbay/proprietary/lib/arm/libpowermanager.so:system/lib/arm/libpowermanager.so \
    vendor/dell/saltbay/proprietary/lib/arm/libRScpp.so:system/lib/arm/libRScpp.so \
    vendor/dell/saltbay/proprietary/lib/arm/libRSCpuRef.so:system/lib/arm/libRSCpuRef.so \
    vendor/dell/saltbay/proprietary/lib/arm/libRSDriver.so:system/lib/arm/libRSDriver.so \
    vendor/dell/saltbay/proprietary/lib/arm/libRS.so:system/lib/arm/libRS.so \
    vendor/dell/saltbay/proprietary/lib/arm/libselinux.so:system/lib/arm/libselinux.so \
    vendor/dell/saltbay/proprietary/lib/arm/libskia.so:system/lib/arm/libskia.so \
    vendor/dell/saltbay/proprietary/lib/arm/libsonivox.so:system/lib/arm/libsonivox.so \
    vendor/dell/saltbay/proprietary/lib/arm/libspeexresampler.so:system/lib/arm/libspeexresampler.so \
    vendor/dell/saltbay/proprietary/lib/arm/libsqlite.so:system/lib/arm/libsqlite.so \
    vendor/dell/saltbay/proprietary/lib/arm/libssl.so:system/lib/arm/libssl.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright_avc_common.so:system/lib/arm/libstagefright_avc_common.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright_enc_common.so:system/lib/arm/libstagefright_enc_common.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright_foundation.so:system/lib/arm/libstagefright_foundation.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright_omx.so:system/lib/arm/libstagefright_omx.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright.so:system/lib/arm/libstagefright.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstagefright_yuv.so:system/lib/arm/libstagefright_yuv.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstdc++.so:system/lib/arm/libstdc++.so \
    vendor/dell/saltbay/proprietary/lib/arm/libstlport.so:system/lib/arm/libstlport.so \
    vendor/dell/saltbay/proprietary/lib/arm/libsurfaceflinger.so:system/lib/arm/libsurfaceflinger.so \
    vendor/dell/saltbay/proprietary/lib/arm/libsync.so:system/lib/arm/libsync.so \
    vendor/dell/saltbay/proprietary/lib/arm/libsysutils.so:system/lib/arm/libsysutils.so \
    vendor/dell/saltbay/proprietary/lib/arm/libui.so:system/lib/arm/libui.so \
    vendor/dell/saltbay/proprietary/lib/arm/libusbhost.so:system/lib/arm/libusbhost.so \
    vendor/dell/saltbay/proprietary/lib/arm/libutils.so:system/lib/arm/libutils.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideochat_jni.so:system/lib/arm/libvideochat_jni.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideoeditor_core.so:system/lib/arm/libvideoeditor_core.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideoeditor_jni.so:system/lib/arm/libvideoeditor_jni.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideoeditor_osal.so:system/lib/arm/libvideoeditor_osal.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideoeditor_videofilters.so:system/lib/arm/libvideoeditor_videofilters.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvideoeditorplayer.so:system/lib/arm/libvideoeditorplayer.so \
    vendor/dell/saltbay/proprietary/lib/arm/libvorbisidec.so:system/lib/arm/libvorbisidec.so \
    vendor/dell/saltbay/proprietary/lib/arm/libwebrtc_audio_coding.so:system/lib/arm/libwebrtc_audio_coding.so \
    vendor/dell/saltbay/proprietary/lib/arm/libwilhelm.so:system/lib/arm/libwilhelm.so \
    vendor/dell/saltbay/proprietary/lib/arm/libwpa_client.so:system/lib/arm/libwpa_client.so \
    vendor/dell/saltbay/proprietary/lib/arm/libz_orig.so:system/lib/arm/libz_orig.so \
    vendor/dell/saltbay/proprietary/lib/arm/libz.so:system/lib/arm/libz.so \
    vendor/dell/saltbay/proprietary/lib/arm/linker:system/lib/arm/linker \
    vendor/dell/saltbay/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/dell/saltbay/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
    vendor/dell/saltbay/proprietary/vendor/bin/hwperfbin2jsont:system/vendor/bin/hwperfbin2jsont \
    vendor/dell/saltbay/proprietary/vendor/bin/pvrdebug:system/vendor/bin/pvrdebug \
    vendor/dell/saltbay/proprietary/vendor/bin/pvrhwperf:system/vendor/bin/pvrhwperf \
    vendor/dell/saltbay/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/dell/saltbay/proprietary/vendor/bin/pvrtld:system/vendor/bin/pvrtld \
    vendor/dell/saltbay/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/dell/saltbay/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/dell/saltbay/proprietary/vendor/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
    vendor/dell/saltbay/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:system/vendor/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/dell/saltbay/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/dell/saltbay/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/dell/saltbay/proprietary/vendor/lib/hw/gralloc.merrifield.so:system/vendor/lib/hw/gralloc.merrifield.so \
    vendor/dell/saltbay/proprietary/lib/libaudioresample.so:system/lib/libaudioresample.so \
    vendor/dell/saltbay/proprietary/lib/libevent-listener.so:system/lib/libevent-listener.so \
    vendor/dell/saltbay/proprietary/lib/libinterface-provider-lib.so:system/lib/libinterface-provider-lib.so \
    vendor/dell/saltbay/proprietary/lib/libinterface-provider.so:system/lib/libinterface-provider.so \
    vendor/dell/saltbay/proprietary/lib/libdsp.so:system/lib/libdsp.so \
    vendor/dell/saltbay/proprietary/lib/libimf.so:system/lib/libimf.so \
    vendor/dell/saltbay/proprietary/lib/libpower.so:system/lib/libpower.so \
    vendor/dell/saltbay/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/dell/saltbay/proprietary/lib/libutaos.so:system/lib/libutaos.so \
    vendor/dell/saltbay/proprietary/lib/libproperty.so:system/lib/libproperty.so \
    vendor/dell/saltbay/proprietary/lib/hw/audio.codec_offload.saltbay.so:system/lib/hw/audio.codec_offload.saltbay.so \
    vendor/dell/saltbay/proprietary/lib/hw/audio.hdmi.saltbay.so:system/lib/hw/audio.hdmi.saltbay.so \
    vendor/dell/saltbay/proprietary/lib/hw/audio.primary.saltbay.so:system/lib/hw/audio.primary.saltbay.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libdsp-subsystem.so:system/lib/parameter-framework-plugins/Audio/libdsp-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libimc-subsystem.so:system/lib/parameter-framework-plugins/Audio/libimc-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libpower-subsystem.so:system/lib/parameter-framework-plugins/Audio/libpower-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Audio/libuta-subsystem.so:system/lib/parameter-framework-plugins/Audio/libuta-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/System/libproperty-subsystem.so:system/lib/parameter-framework-plugins/System/libproperty-subsystem.so \
    vendor/dell/saltbay/proprietary/lib/parameter-framework-plugins/Fs/libfs-subsystem.so:system/lib/parameter-framework-plugins/Fs/libfs-subsystem.so \
    #vendor/dell/saltbay/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    #vendor/dell/saltbay/proprietary/vendor/etc/audio_offload_effects.conf:system/vendor/etc/audio_offload_effects.conf \
    vendor/dell/saltbay/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/dell/saltbay/proprietary/lib/hw/gps.saltbay.so:system/lib/hw/gps.saltbay.so \
    vendor/dell/saltbay/proprietary/lib/hw/lights.saltbay.so:system/lib/hw/lights.saltbay.so
